import type { Vaga, Candidatura, ChatConversation, ChatMessage, Denuncia } from "./types"

export const MOCK_VAGAS: Vaga[] = [
  {
    id: "v1",
    titulo: "Ajudante de Evento",
    categoria: "Eventos e Atendimento",
    categoriaId: "eventos-atendimento",
    descricao: "Precisamos de ajudante para montagem e desmontagem de evento corporativo. Inclui apoio na organizacao de mesas, cadeiras e decoracao. Refeicao inclusa.",
    requisitos: ["Pontualidade", "Boa comunicacao", "Disposicao fisica"],
    valor: "R$ 120/dia",
    tipo: "presencial",
    endereco: "Rua das Flores, 123 - Centro",
    cidade: "Fortaleza",
    dataInicio: "15/02/2026",
    dataFim: "15/02/2026",
    horarioInicio: "07:00",
    horarioFim: "17:00",
    qtdVagas: 3,
    qtdCandidatos: 8,
    status: "publicada",
    urgencia: "alta",
    contratanteId: "c1",
    contratanteNome: "Buffet Sabor & Arte",
    contratanteTipo: "pj",
    contratanteAvaliacao: 4.7,
    contratanteTempoPlataforma: "6 meses",
    distancia: "2.3 km",
    habilidades: ["ajudante-eventos"],
    criadaEm: "2026-02-12T10:00:00Z",
  },
  {
    id: "v2",
    titulo: "Limpeza Pos-Obra",
    categoria: "Casa e Rotina",
    categoriaId: "casa-rotina",
    descricao: "Limpeza completa pos-obra de apartamento de 80m2. Inclui remocao de entulho leve, limpeza de pisos, vidros e banheiros.",
    requisitos: ["Experiencia com limpeza", "Trazer material basico"],
    valor: "R$ 150/dia",
    tipo: "presencial",
    endereco: "Av. Santos Dumont, 456 - Aldeota",
    cidade: "Fortaleza",
    dataInicio: "14/02/2026",
    dataFim: "14/02/2026",
    horarioInicio: "08:00",
    horarioFim: "16:00",
    qtdVagas: 2,
    qtdCandidatos: 5,
    status: "publicada",
    urgencia: "alta",
    contratanteId: "c2",
    contratanteNome: "Construtora Nova Era",
    contratanteTipo: "pj",
    contratanteAvaliacao: 4.3,
    contratanteTempoPlataforma: "1 ano",
    distancia: "4.1 km",
    habilidades: ["limpeza-casa"],
    criadaEm: "2026-02-12T09:30:00Z",
  },
  {
    id: "v3",
    titulo: "Garcom para Casamento",
    categoria: "Eventos e Atendimento",
    categoriaId: "eventos-atendimento",
    descricao: "Servir bebidas e finger food em casamento para 200 convidados. Uniforme fornecido (camisa branca + avental). Experiencia anterior desejavel.",
    requisitos: ["Experiencia como garcom", "Boa apresentacao", "Disponibilidade noturna"],
    valor: "R$ 180/dia",
    tipo: "presencial",
    endereco: "Chacara Celebrar - Messejana",
    cidade: "Fortaleza",
    dataInicio: "16/02/2026",
    horarioInicio: "18:00",
    horarioFim: "02:00",
    qtdVagas: 5,
    qtdCandidatos: 12,
    status: "publicada",
    urgencia: "media",
    contratanteId: "c3",
    contratanteNome: "Espaco Celebrar",
    contratanteTipo: "pj",
    contratanteAvaliacao: 4.9,
    contratanteTempoPlataforma: "2 anos",
    distancia: "8.5 km",
    habilidades: ["garcom-copeiro"],
    criadaEm: "2026-02-11T14:00:00Z",
  },
  {
    id: "v4",
    titulo: "Entregador por Turno",
    categoria: "Fretes e Logistica",
    categoriaId: "fretes-logistica",
    descricao: "Entregas de medicamentos na regiao metropolitana. Moto propria necessaria. Combustivel por conta da farmacia.",
    requisitos: ["CNH A/B", "Moto propria", "Conhecer a cidade"],
    valor: "R$ 90/turno",
    tipo: "presencial",
    endereco: "Farmacia Popular - Benfica",
    cidade: "Fortaleza",
    dataInicio: "13/02/2026",
    horarioInicio: "08:00",
    horarioFim: "14:00",
    qtdVagas: 2,
    qtdCandidatos: 4,
    status: "publicada",
    urgencia: "normal",
    contratanteId: "c4",
    contratanteNome: "Farmacia Popular",
    contratanteTipo: "pj",
    contratanteAvaliacao: 4.1,
    contratanteTempoPlataforma: "3 meses",
    distancia: "3.2 km",
    habilidades: ["entregas-delivery", "motoboy-turno"],
    criadaEm: "2026-02-10T11:00:00Z",
  },
  {
    id: "v5",
    titulo: "Cuidador de Idoso - FDS",
    categoria: "Cuidados",
    categoriaId: "cuidados",
    descricao: "Acompanhar idosa de 78 anos durante o fim de semana. Atividades: companhia, preparo de refeicoes leves, auxilio com medicacao. Quarto disponivel.",
    requisitos: ["Experiencia com idosos", "Paciencia", "Referencias"],
    valor: "R$ 200/dia",
    tipo: "presencial",
    endereco: "Rua Padre Valdevino - Papicu",
    cidade: "Fortaleza",
    dataInicio: "15/02/2026",
    dataFim: "16/02/2026",
    horarioInicio: "08:00",
    horarioFim: "20:00",
    qtdVagas: 1,
    qtdCandidatos: 3,
    status: "publicada",
    urgencia: "media",
    contratanteId: "c5",
    contratanteNome: "Familia Sousa",
    contratanteTipo: "pf",
    contratanteAvaliacao: 5.0,
    contratanteTempoPlataforma: "4 meses",
    distancia: "5.7 km",
    habilidades: ["cuidar-idoso"],
    criadaEm: "2026-02-11T09:00:00Z",
  },
  {
    id: "v6",
    titulo: "Panfletagem em Shopping",
    categoria: "Comercial e Divulgacao",
    categoriaId: "comercial-divulgacao",
    descricao: "Distribuicao de panfletos e abordagem de clientes na entrada do shopping. Material fornecido. Necessario boa comunicacao.",
    requisitos: ["Simpatia", "Boa comunicacao", "Proatividade"],
    valor: "R$ 80/turno",
    tipo: "presencial",
    endereco: "Shopping Iguatemi",
    cidade: "Fortaleza",
    dataInicio: "17/02/2026",
    horarioInicio: "10:00",
    horarioFim: "14:00",
    qtdVagas: 4,
    qtdCandidatos: 7,
    status: "publicada",
    urgencia: "normal",
    contratanteId: "c6",
    contratanteNome: "Loja TechStore",
    contratanteTipo: "pj",
    contratanteAvaliacao: 3.8,
    contratanteTempoPlataforma: "1 mes",
    distancia: "6.0 km",
    habilidades: ["panfletagem"],
    criadaEm: "2026-02-12T08:00:00Z",
  },
]

export const MOCK_CANDIDATURAS: Candidatura[] = [
  {
    id: "cand1",
    vagaId: "v1",
    vagaTitulo: "Ajudante de Evento",
    vagaValor: "R$ 120/dia",
    vagaData: "Sab, 15/02",
    vagaLocal: "Centro, Fortaleza",
    candidatoId: "user-1",
    candidatoNome: "Maria Silva",
    contratanteId: "c1",
    contratanteNome: "Buffet Sabor & Arte",
    status: "selecionado",
    mensagemInicial: "Tenho experiencia com eventos, estou disponivel!",
    criadaEm: "2026-02-12T10:30:00Z",
  },
  {
    id: "cand2",
    vagaId: "v3",
    vagaTitulo: "Garcom para Casamento",
    vagaValor: "R$ 180/dia",
    vagaData: "Dom, 16/02",
    vagaLocal: "Messejana, Fortaleza",
    candidatoId: "user-1",
    candidatoNome: "Maria Silva",
    contratanteId: "c3",
    contratanteNome: "Espaco Celebrar",
    status: "em_analise",
    criadaEm: "2026-02-11T15:00:00Z",
  },
  {
    id: "cand3",
    vagaId: "v2",
    vagaTitulo: "Limpeza Pos-Obra",
    vagaValor: "R$ 150/dia",
    vagaData: "Sex, 07/02",
    vagaLocal: "Aldeota, Fortaleza",
    candidatoId: "user-1",
    candidatoNome: "Maria Silva",
    contratanteId: "c2",
    contratanteNome: "Construtora Nova Era",
    status: "enviada",
    criadaEm: "2026-02-12T11:00:00Z",
  },
]

export const MOCK_CONVERSATIONS: ChatConversation[] = [
  {
    id: "conv1",
    vagaId: "v1",
    vagaTitulo: "Ajudante de Evento",
    participantId: "c1",
    participantName: "Buffet Sabor & Arte",
    lastMessage: "Otimo! Entao te espero sabado as 7h.",
    lastMessageAt: "12:45",
    unreadCount: 1,
  },
  {
    id: "conv2",
    vagaId: "v3",
    vagaTitulo: "Garcom para Casamento",
    participantId: "c3",
    participantName: "Espaco Celebrar",
    lastMessage: "Voce tem experiencia servindo em eventos grandes?",
    lastMessageAt: "Ontem",
    unreadCount: 0,
  },
]

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  conv1: [
    { id: "m1", vagaId: "v1", senderId: "user-1", senderName: "Maria Silva", text: "Ola! Me candidatei para a vaga de ajudante de evento. Tenho experiencia com eventos!", timestamp: "10:30" },
    { id: "m2", vagaId: "v1", senderId: "c1", senderName: "Buffet Sabor & Arte", text: "Oi Maria! Que bom. Voce ja trabalhou com montagem de mesas e decoracao?", timestamp: "10:45" },
    { id: "m3", vagaId: "v1", senderId: "user-1", senderName: "Maria Silva", text: "Sim! Ja trabalhei em 3 eventos de buffet no ultimo mes.", timestamp: "11:00" },
    { id: "m4", vagaId: "v1", senderId: "c1", senderName: "Buffet Sabor & Arte", text: "Perfeito! Voce esta selecionada. O evento e sabado, comecar as 7h no Centro.", timestamp: "12:30" },
    { id: "m5", vagaId: "v1", senderId: "c1", senderName: "Buffet Sabor & Arte", text: "Otimo! Entao te espero sabado as 7h.", timestamp: "12:45" },
  ],
  conv2: [
    { id: "m6", vagaId: "v3", senderId: "c3", senderName: "Espaco Celebrar", text: "Oi! Obrigado por se candidatar. Voce tem experiencia servindo em eventos grandes?", timestamp: "Ontem" },
  ],
}

export const MOCK_DENUNCIAS: Denuncia[] = [
  {
    id: "d1",
    tipo: "usuario",
    reportadoId: "user-x",
    reportadoNome: "Jose Fake",
    denuncianteId: "c3",
    motivo: "Perfil falso",
    descricao: "Usuario com foto e dados falsos. Nao compareceu ao evento.",
    status: "pendente",
    criadaEm: "2026-02-11T10:00:00Z",
  },
  {
    id: "d2",
    tipo: "vaga",
    reportadoId: "v-x",
    reportadoNome: "Vaga Suspeita - Trabalho noturno",
    denuncianteId: "user-1",
    motivo: "Conteudo inapropriado",
    descricao: "Vaga com descricao vaga e suspeita, possivelmente golpe.",
    status: "analisando",
    criadaEm: "2026-02-10T14:00:00Z",
  },
  {
    id: "d3",
    tipo: "usuario",
    reportadoId: "c-x",
    reportadoNome: "Empresa XYZ",
    denuncianteId: "user-2",
    motivo: "Nao pagou",
    descricao: "Contratante nao efetuou o pagamento apos conclusao do servico.",
    status: "pendente",
    criadaEm: "2026-02-09T16:00:00Z",
  },
]

export const CANDIDATURA_STATUS_LABELS: Record<string, string> = {
  enviada: "Enviada",
  em_analise: "Em analise",
  convidado: "Convite recebido",
  selecionado: "Selecionado",
  recusado: "Recusado",
  cancelado: "Cancelado",
  no_show: "No-show",
}

export const CANDIDATURA_STATUS_STYLES: Record<string, string> = {
  enviada: "bg-primary/10 text-primary",
  em_analise: "bg-warning/10 text-warning",
  convidado: "bg-accent/10 text-accent",
  selecionado: "bg-accent/10 text-accent",
  recusado: "bg-destructive/10 text-destructive",
  cancelado: "bg-muted text-muted-foreground",
  no_show: "bg-destructive/10 text-destructive",
}

export const VAGA_STATUS_LABELS: Record<string, string> = {
  rascunho: "Rascunho",
  publicada: "Publicada",
  pausada: "Pausada",
  preenchida: "Preenchida",
  em_andamento: "Em andamento",
  concluida: "Concluida",
  cancelada: "Cancelada",
  expirada: "Expirada",
}

export const VAGA_STATUS_STYLES: Record<string, string> = {
  rascunho: "bg-muted text-muted-foreground",
  publicada: "bg-accent/10 text-accent",
  pausada: "bg-warning/10 text-warning",
  preenchida: "bg-primary/10 text-primary",
  em_andamento: "bg-primary/10 text-primary",
  concluida: "bg-muted text-muted-foreground",
  cancelada: "bg-destructive/10 text-destructive",
  expirada: "bg-muted text-muted-foreground",
}
